esphome:
  name: "ardn-coop-door-dev"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-1B3A48"
    password: "qLBTB6qCUPM4"
    

captive_portal:

status_led:
  pin:
    number: GPIO5
    inverted: true

button:
  - platform: template
    name: "Open Coop Door"
    id: openCoopDoorBtn
    icon: "mdi:garage-open"
    on_press:
      then:
        - if:
            condition:
              switch.is_on: closedLED
            then:
              - script.execute: openCoopDoor

  - platform: template
    name: "Close Coop Door"
    id: closeCoopDoorBtn
    icon: "mdi:garage"
    on_press:
      then:
        - if:
            condition:
              switch.is_on: openLED
            then:
              - script.execute: closeCoopDoor

switch:
  - platform: gpio
    name: "wifi connected"
    pin: GPIO25
    id: wifiConnected
    icon: "mdi:wifi-check"

  - platform: gpio
    name: "door stopped"
    pin: GPIO26
    id: doorStopped
    icon: "mdi:alert-octagon"

  - platform: gpio
    name: "Door is Open"
    pin: GPIO2
    id: openLED
    icon: "mdi:led-variant-outline"

  - platform: gpio
    name: "Door is Closed"
    pin: GPIO15
    id: closedLED
    icon: "mdi:led-variant-outline"

  - platform: gpio
    name: "Door is Moving"
    pin: GPIO4
    id: movingLED
    icon: "mdi:led-variant-outline"

  - platform: gpio
    name: "Opening the Door"
    pin: GPIO13
    id: openMotor
    icon: "mdi:garage-open"

  - platform: gpio
    name: "Closing the Door"
    pin: GPIO12
    id: closeMotor
    icon: "mdi:garage"
    
binary_sensor:
  - platform: gpio
    entity_category: diagnostic
    name: "door open"
    pin: GPIO34
    icon: "mdi:garage-open"
    on_press:
      then:
        - switch.turn_off: openMotor
        - switch.turn_off: movingLED
        - switch.turn_on: openLED
        - script.stop: openCoopDoor
    on_release:
      then:
        - switch.turn_off: openLED
        - switch.turn_on: movingLED

  - platform: gpio
    entity_category: diagnostic
    name: "door closed"
    pin: GPIO32
    icon: "mdi:garage"
    on_press:
      then:
        - switch.turn_off: closeMotor
        - switch.turn_off: movingLED
        - switch.turn_on: closedLED
        - script.stop: closeCoopDoor
    on_release:
      then:
        - switch.turn_off: closedLED
        - switch.turn_on: movingLED

  - platform: gpio
    name: "Local Open Button"
    pin: GPIO23
    id: localOpenButton
    on_press:
      then:
        - if:
            condition:
              switch.is_on: closedLED
            then:
              - script.execute: openCoopDoor
        - if:
            condition:
              switch.is_on: doorStopped
            then:
              - script.execute: openCoopDoor

  - platform: gpio
    name: "Local Stop Button"
    pin: GPIO22
    id: localStopButton
    on_press:
      then:
        - if:
            condition:
              switch.is_on: movingLED
            then:
              - script.execute: stopCoopDoor
              - script.stop: openCoopDoor
              - script.stop: closeCoopDoor

  - platform: gpio
    name: "Local Close Button"
    pin: GPIO21
    id: localCloseButton
    on_press:
      then:
        - if:
            condition:
              switch.is_on: openLED
            then:
              - script.execute: closeCoopDoor
        - if:
            condition:
              switch.is_on: doorStopped
            then:
              - script.execute: closeCoopDoor

  - platform: gpio
    name: "Local Top Button"
    pin: GPIO27
    id: localTopButton
    on_press:
      then:
        - switch.turn_off: closeMotor
        - delay: 100ms
        - switch.turn_on: openMotor
    on_release:
      then:
        - switch.turn_off: openMotor

  - platform: gpio
    name: "Local Bottom Button"
    pin: GPIO33
    id: localBottomButton
    on_press:
      then:
        - switch.turn_off: openMotor
        - delay: 100ms
        - switch.turn_on: closeMotor
    on_release:
      then:
        - switch.turn_off: closeMotor

script:
  - id: openCoopDoor
    then:
      - switch.turn_off: doorStopped
      - switch.turn_off: closeMotor
      - delay: 100ms
      - switch.turn_on: openMotor
      - delay: 30s
      - switch.turn_off: openMotor

  - id: closeCoopDoor
    then:
      - switch.turn_off: doorStopped
      - switch.turn_off: openMotor
      - delay: 100ms
      - switch.turn_on: closeMotor
      - delay: 30s
      - switch.turn_off: closeMotor

  - id: stopCoopDoor
    then:
      - switch.turn_off: openMotor
      - switch.turn_off: closeMotor
      - switch.turn_off: movingLED
      - switch.turn_on: doorStopped

